### PR TITLE
FIX: #51.

### PR DESCRIPTION
**Pull request by earcanal**
I'm guessing auto preloading runs _after_ the HTML is added to the image
URLs.

### CODE REVIEW

**Comment by vsoch** [comment]
hey let's get the CI working for attention network task first, then we can add here (and merge fixes) sound good?

**Comment by earcanal** [comment]
OK.  What's ANT waiting for?

**Comment by vsoch** [comment]
Do you have tests for this one?

**Comment by earcanal** [comment]
The only test is that the 404s are now gone.

**Comment by vsoch** [comment]
ok so let me see if I can give the expfactory-robots a shot for this CI.

**Comment by vsoch** [comment]
This will close when https://github.com/expfactory-experiments/local-global-shape/pull/3 is merged.

**Pull request merged**
